#!/usr/bin/env node
// Builds js/icons.js: the Lucide icons the app uses, so icons show offline and
// from file:// without the CDN. Run after adding a data-lucide="..." icon:
//
//   npm pack lucide@0.475.0 && tar xzf lucide-0.475.0.tgz
//   node scripts/build-icons.js package/dist/umd/lucide.js
//
// Icon names are collected from index.html, app.js and js/*.js, including
// names inside ${cond ? 'a' : 'b'} template expressions.
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const src = process.argv[2];
if (!src) { console.error('usage: node scripts/build-icons.js path/to/lucide.js'); process.exit(1); }

const g = {};
new Function('self', 'globalThis', 'exports', 'module', 'define', fs.readFileSync(src, 'utf8'))(g, g);
const { icons } = g.lucide;
const version = (fs.readFileSync(src, 'utf8').match(/lucide v([\d.]+)/) || [])[1] || '?';

const files = ['index.html', 'app.js', ...fs.readdirSync(path.join(ROOT, 'js')).filter(f => f.endsWith('.js') && f !== 'icons.js').map(f => 'js/' + f)];
const names = new Set();
for (const f of files) {
    const text = fs.readFileSync(path.join(ROOT, f), 'utf8');
    for (const m of text.matchAll(/data-lucide="([^"]+)"/g)) {
        const found = m[1].includes('${') ? [...m[1].matchAll(/'([a-z0-9-]+)'/g)].map(x => x[1]) : [m[1]];
        for (const n of found) names.add(n);
    }
}
const pascal = n => n.replace(/(^|-)([a-z0-9])/g, (_, a, b) => b.toUpperCase());
const out = {};
for (const n of [...names].sort()) {
    const node = icons[pascal(n)];
    if (node) out[n] = node;
}

fs.writeFileSync(path.join(ROOT, 'js/icons.js'), `// Generated by scripts/build-icons.js from Lucide v${version} (ISC license,
// https://lucide.dev). Holds only the icons the app uses; do not edit by hand.
// Provides lucide.createIcons(), replacing each element with data-lucide="name"
// (an <i>, or an icon rendered earlier whose name has since changed) with its SVG.
const LUCIDE_ICONS = ${JSON.stringify(out)};

window.lucide = {
    createIcons() {
        const NS = 'http://www.w3.org/2000/svg';
        for (const el of document.querySelectorAll('[data-lucide]')) {
            const name = el.getAttribute('data-lucide');
            const node = LUCIDE_ICONS[name];
            if (!node) continue;
            const svg = document.createElementNS(NS, 'svg');
            const attrs = { xmlns: NS, width: 24, height: 24, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor',
                'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round', 'aria-hidden': 'true' };
            for (const [k, v] of Object.entries(attrs)) svg.setAttribute(k, v);
            for (const a of el.attributes) if (a.name !== 'data-lucide') svg.setAttribute(a.name, a.value);
            const keep = (el.getAttribute('class') || '').split(/\\s+/).filter(c => c && !c.startsWith('lucide'));
            svg.setAttribute('class', ['lucide', 'lucide-' + name, ...keep].join(' '));
            for (const [tag, a] of node) {
                const child = document.createElementNS(NS, tag);
                for (const [k, v] of Object.entries(a)) child.setAttribute(k, v);
                svg.appendChild(child);
            }
            el.replaceWith(svg);
        }
    },
};
`);
console.log(`js/icons.js: ${Object.keys(out).length} icons (${[...names].filter(n => !out[n]).join(', ') || 'none missing'})`);
